### ISSUE TITLE
an option to fail compliation in case of errors

### ISSUE THREAD

**Issue by michael-go** [diegodurli/flow-status-webpack-plugin#11]
Hi,

it can be great if the there will be an option to fail the webpack build in case Flow detects errors.

thanks

**Comment by moljac024** [comment]
Hey, I hacked something together that achieves this.

Take a look at [my fork](https://github.com/moljac024/flow-status-webpack-plugin). I'll create a pull request a little later, since I made more changes than are needed, and am still testing the approach. I'm not super happy with the implementation, but hopefully it works good enough for a start.

**Comment by randallb** [comment]
@moljac024 since your fork doesn't have issues, I'll leave this here. The error notification (in console) for me only shows up on the first error (while I'm watching). I'd like for it to show up every time. Any idea why that might be? Also, thank you for your work! 😄

**Comment by diegodurli** [comment]
Hi @michael-go and @moljac024!

I think this can be a good feature to have in place.
You're going into the right path @moljac024, mainly because this change requires a good refactoring, since it changes when we can flow checking. It introduces a new phase, and I think you're right assuming `compilation` phase as the proper one.

You're more than welcome to send over your PR for this, then we can discuss it more.

Thanks guys!

**Comment by kayneb** [comment]
Doesn't this already exist? Have a look at `failOnError` - https://github.com/diegodurli/flow-status-webpack-plugin/blob/master/index.js
